algorithm: visualbc_buffer_collector

# env:
#   category: dmc
#   domain_name: finger
#   task_name: spin
#   frame_stack: 3
#   action_repeat: 4
#   image_size: 100
#   episode_length: 1000
#   eval_mode: null
#   distracting_cs_intensity: 0 # 

env:
  category: custom_metaworld
  env_id: button-press-wall-v2
  # whether randomize the task
  robust: true
  random_level: 0
  # how many random tasks to collect
  # set 60 to be fully random
  diversity: 3
  frame_stack: 3
  mode: rgb
  image_size: 140
  camera_id: 2

agent:
  model_path: ./ckpts/custom_metaworld/button-press-wall-v2/button-press-wall-v2-level-4.pt

algo:
  seed: 2
  rollout_steps: 1000
  batch_size: 128
  save_video: true
  log_dir: logs
