algorithm: visualbc_buffer_collector

# env:
#   category: dmc
#   domain_name: finger
#   task_name: spin
#   frame_stack: 3
#   action_repeat: 4
#   image_size: 100
#   episode_length: 1000
#   eval_mode: null
#   distracting_cs_intensity: 0 # 

env:
  category: custom_metaworld
  env_id: door-close-v2
  # whether randomize the task
  robust: false
  frame_stack: 3
  mode: rgb
  image_size: 140
  camera_id: 2

agent:
  model_path: "./ckpts/custom_metaworld/door-close-v2-level-1.pt"

algo:
  seed: 42
  rollout_steps: 20000
  batch_size: 128
  save_video: true
  log_dir: logs
