algorithm: crd_bc

env:
  category: custom_metaworld
  env_id: reach-wall-v2
  robust: false
  frame_stack: 3
  mode: rgb
  image_size: 140
  camera_id: 2

agent:
  name: crd_bc # not used
  use_aug: ${algo.crop}
  hidden_dim: 1024 
  num_shared_layers: 11 
  num_head_layers: 0 
  num_filters: 32 
  projection_dim: 100 
  actor_beta: 0.9 
  bc_lr: 0.001 # bc
  use_crd: true
  lambda_crd: 0.8 # crd weight
  s_dims: [1024, 1024, 1024]
  t_dims: [512, 512, 512]
  crd_weight: [
    [0.0, 0.0, 0.0],
    [0.0, 0.5, 0.0],
    [0.0, 0.0, 0.5],
  ]
  feat_dim: ${algo.feature_dim}
  nce_k: 4096
  n_data: 1000 # depends on the expert buffer size
  T: 0.07
  momentum: 0.5
  use_edge_sim: false
  lambda_es: 0.8
  es_weight: [
    [0.3, 0.0, 0.0],
    [0.0, 0.3, 0.0],
    [0.0, 0.0, 0.4],
  ]
  es_size: 128
  es_normalize: true
  # whether to store the contrastive memory in gpu
  contrastive_memory_in_gpu: true
  mode: "visual" # not used
  visual_contrastive_task: false # if set true will use strong aug for auged contrastive

expert:
  name: state_sac
  mode: "state" # not used
  hidden_dim: 512 # not used
  model_path: ./ckpts/custom_metaworld/reach-wall-v2/reach-wall-v2-level-4.pt
  buffer_path: ./buffers/custom_metaworld/diversity/reach-wall-v2/diversity_3.pkl

algo:
  seed: 42
  train_steps: 100000 # 500000
  batch_size: 128
  save_freq: 20000
  eval_freq: 10000
  # eval_episodes: 1
  eval_episodes: 0
  feature_dim: 512
  crop: weak
  image_crop_size: 124
  log_dir: logs
  save_video: true #
  use_wandb: false #
