algorithm: crd_bc_strong_aug

env:
  domain_name: finger
  task_name: spin
  frame_stack: 3
  action_repeat: 4
  image_size: 100
  episode_length: 1000
  eval_mode: null
  distracting_cs_intensity: 0

agent:
  name: crd_bc # not used
  use_aug: ${algo.crop}
  hidden_dim: 1024 
  num_shared_layers: 11 
  num_head_layers: 0 
  num_filters: 32 
  projection_dim: 100 
  actor_beta: 0.9 
  bc_lr: 0.001 # bc
  lambda_crd: 0.8 # crd weight
  s_dim: ${agent.hidden_dim}
  t_dim: 256
  feat_dim: ${algo.feature_dim}
  nce_k: ${algo.K}
  n_data: 50000 # depends on the expert buffer size
  mode: "visual" # not used
  visual_contrastive_task: false # if set true will use strong aug for auged contrastive

expert:
  name: state_sac
  mode: "state" # not used
  hidden_dim: 256 # not used
  model_path: ./ckpts/state_v1.pt
  buffer_path: ./buffers/50000_intensity0.pkl

algo:
  seed: 42
  train_steps: 200000 # 500000
  batch_size: 128
  save_freq: 50000
  eval_freq: 10000
  eval_episodes: 30
  feature_dim: 256
  K: 4096
  T: 0.07
  momentum: 0.5
  crop: "strong"
  image_crop_size: 84
  log_dir: logs
  save_video: true #
  use_wandb: true #
