algos: {
  'bc': experiment_records/1_18/bc.pt,
  'crd_bc': experiment_records/1_18/crd_bc.pt,
  'crd_one': experiment_records/1_24/crd_one.pt,
  'crd_es_norm': experiment_records/1_24/crd_es_norm.pt,
  'crd_es': experiment_records/1_24/crd_es.pt,
  'no_crd_64': experiment_records/1_23/es/no_crd_64.pt,
  'no_crd_128': experiment_records/1_24/no_crd_128.pt,
}

seed: 42
save_video: true
eval_episodes: 30
# eval_episodes: 5
log_dir: logs

env:
  robust: true
  env_ids: [
    button-press-topdown-v2,
    drawer-close-v2,
    drawer-open-v2,
    window-close-v2,
    window-open-v2,
  ]
  frame_stack: 3
  mode: rgb
  image_size: 140
  camera_id: 2
