algos: {
  "vanilla_visual_sac": "ckpts/visual.pt",
  "vanilla_state_sac": "ckpts/state.pt",
  "vanilla_aac": "ckpts/aac.pt",
  "vanilla_bc": "ckpts/bc.pt",
} # all of the models are 200000 steps training
intensities: [0.1, 0.2, 0.3, 0.4, 0.5]
save_video: true
eval_episodes: 10

env:
  domain_name: finger
  task_name: spin
  frame_stack: 3
  action_repeat: 4
  image_size: 100
  episode_length: 1000
  eval_mode: null
  distracting_cs_intensity: null # leave this to null
