algos: {
  'bc': experiment_records/2_15/reach-wall-v2/bc.pt,
  'crd': experiment_records/2_15/reach-wall-v2/crd.pt,
  'longer_crd': experiment_records/2_15/reach-wall-v2/longer_crd.pt,
  'mlp_crd': experiment_records/2_15/reach-wall-v2/mlp_crd.pt,
}

seed: 42
save_video: true
eval_episodes: 50
# eval_episodes: 5
log_dir: logs

env:
  env_id: reach-wall-v2
  frame_stack: 3
  mode: rgb
  image_size: 140
  camera_id: 2
