algos: {
  'bc': experiment_records/1_26/bc.pt,
  'use_ea': experiment_records/1_27/use_ea.pt,
  'pure_crd': experiment_records/1_27/pure_crd.pt,
  'pure_crd_ea': experiment_records/1_27/pure_crd_ea.pt,
}

seed: 42
save_video: true
eval_episodes: 50
# eval_episodes: 5
log_dir: logs

env:
  env_id: door-close-v2
  frame_stack: 3
  mode: rgb
  image_size: 140
  camera_id: 2
