# algos: {
#   'state': ckpts/state_v1.pt,
#   'bc': ckpts/bc_50k.pt,
#   'crd_bc': ckpts/crdbc_50k.pt,
#   'crd_bc_contrast': ckpts/crdbc_contrast_50k.pt,
# } # all of the models are 200000 steps training

# algos: {
#   'bc_contrast': ckpts/bc_contrast_50k.pt,
#   'bc_aug': ckpts/bc_highaug_50k.pt,
#   'crd_bc_aug': ckpts/crdbc_highaug_50k.pt,
# } # all of the models are 200000 steps training

algos: {
  'bc_aug_contrast': ckpts/bc_aug_contrast_50k.pt,
  'crd_aug_contrast': ckpts/crdbc_aug_contrast_50k.pt,
} # all of the models are 200000 steps training

intensities: [0.1, 0.2, 0.3]
save_video: true
eval_episodes: 30

env:
  domain_name: finger
  task_name: spin
  frame_stack: 3
  action_repeat: 4
  image_size: 100
  episode_length: 1000
  eval_mode: null
  distracting_cs_intensity: null # leave this to null