algos: {
  'bc': ckpts/strong_aug/bc.pt,
  'crd_bc': ckpts/strong_aug/crd_bc.pt,
  'cross': ckpts/strong_aug/cross.pt,
  'half_proj': ckpts/strong_aug/half_proj.pt,
  'half_proj_cross': ckpts/strong_aug/half_proj_cross.pt,
}

intensities: [0.0, 0.1, 0.2, 0.3]
save_video: true
eval_episodes: 30
log_dir: logs

env:
  category: dmc
  env_id: finger_spin
  domain_name: finger
  task_name: spin
  frame_stack: 3
  action_repeat: 4
  image_size: 100
  episode_length: 1000
  eval_mode: null
  distracting_cs_intensity: null # leave this to null
