algos: {
  'bc_2': experiment_records/1_21/bc/2.pt,
  'bc_3': experiment_records/1_21/bc/3.pt,
  'bc_5': experiment_records/1_21/bc/5.pt,
  'bc_7': experiment_records/1_21/bc/7.pt,
  'bc_11': experiment_records/1_21/bc/11.pt,
  'crd_2': experiment_records/1_21/crd/2.pt,
  'crd_3': experiment_records/1_21/crd/3.pt,
  'crd_5': experiment_records/1_21/crd/5.pt,
  'crd_7': experiment_records/1_21/crd/7.pt,
  'crd_11': experiment_records/1_21/crd/11.pt,
}

seed: 42
save_video: true
eval_episodes: 30
# eval_episodes: 5
log_dir: logs

env:
  robust: true
  env_ids: [
    button-press-topdown-v2,
    drawer-close-v2,
    drawer-open-v2,
    window-close-v2,
    window-open-v2,
  ]
  frame_stack: 3
  mode: rgb
  image_size: 140
  camera_id: 2
