algos: {
  'button-press-topdown-v2': ckpts/multitask/button-press-topdown-v2.pt,
  'drawer-close-v2': ckpts/multitask/drawer-close-v2.pt,
  'drawer-open-v2': ckpts/multitask/drawer-open-v2.pt,
  'window-close-v2': ckpts/multitask/window-close-v2.pt,
  'window-open-v2': ckpts/multitask/window-open-v2.pt,
}

seed: 42
save_video: true
eval_episodes: 30
# eval_episodes: 5
log_dir: logs

env:
  robust: true
  env_ids: [
    button-press-topdown-v2,
    drawer-close-v2,
    drawer-open-v2,
    window-close-v2,
    window-open-v2,
  ]
  frame_stack: 3
  mode: rgb
  image_size: 140
  camera_id: 2
