algos: {'bc': 'ckpts/bc_v2.pt', '0.4_0.0': 'ckpts/distribute_v2/pure_crd_0.4_0.0.pt', '0.0_0.0': 'ckpts/distribute_v2/pure_crd_0.0_0.0.pt', '0.2_0.6': 'ckpts/distribute_v2/pure_crd_0.2_0.6.pt', '0.0_0.2': 'ckpts/distribute_v2/pure_crd_0.0_0.2.pt', '0.4_0.4': 'ckpts/distribute_v2/pure_crd_0.4_0.4.pt', '0.0_0.6': 'ckpts/distribute_v2/pure_crd_0.0_0.6.pt', '0.8_0.0': 'ckpts/distribute_v2/pure_crd_0.8_0.0.pt', '0.6_0.2': 'ckpts/distribute_v2/pure_crd_0.6_0.2.pt', '0.6_0.0': 'ckpts/distribute_v2/pure_crd_0.6_0.0.pt', '0.4_0.2': 'ckpts/distribute_v2/pure_crd_0.4_0.2.pt', '0.2_0.0': 'ckpts/distribute_v2/pure_crd_0.2_0.0.pt', '0.2_0.4': 'ckpts/distribute_v2/pure_crd_0.2_0.4.pt', '0.2_0.8': 'ckpts/distribute_v2/pure_crd_0.2_0.8.pt', '0.0_1.0': 'ckpts/distribute_v2/pure_crd_0.0_1.0.pt', '0.2_0.2': 'ckpts/distribute_v2/pure_crd_0.2_0.2.pt', '0.6_0.4': 'ckpts/distribute_v2/pure_crd_0.6_0.4.pt', '0.4_0.6': 'ckpts/distribute_v2/pure_crd_0.4_0.6.pt', '0.8_0.2': 'ckpts/distribute_v2/pure_crd_0.8_0.2.pt', '0.0_0.4': 'ckpts/distribute_v2/pure_crd_0.0_0.4.pt', '0.0_0.8': 'ckpts/distribute_v2/pure_crd_0.0_0.8.pt'}

intensities: [0.1, 0.2, 0.3]
save_video: true
eval_episodes: 30
log_dir: logs

env:
  category: dmc
  env_id: finger_spin
  domain_name: finger
  task_name: spin
  frame_stack: 3
  action_repeat: 4
  image_size: 100
  episode_length: 1000
  eval_mode: null
  distracting_cs_intensity: null # leave this to null
