algos: {
  'reach-wall-v2': ckpts/custom_metaworld/reach-wall-v2/reach-wall-v2-level-4.pt
}

seed: 42
save_video: true
eval_episodes: 30
# eval_episodes: 5
log_dir: logs

env:
  category: custom_metaworld
  robust: true
  random_level: 4
  env_ids: [
    reach-wall-v2
  ]
  frame_stack: 3
  mode: rgb
  image_size: 140
  camera_id: 2
