# select trainer file
algorithm: vanilla_visual_sac

# select env
env:
  category: metaworld
  env_id: pick-place-v2
  frame_stack: 3
  mode: rgb
  image_size: 140
  camera_id: 2

# select agent file
agent:
  name: visual_sac
  use_aug: ${algo.crop}
  discount: 0.99
  init_temperature: 0.1
  hidden_dim: 1024
  num_shared_layers: 11
  num_head_layers: 0
  num_filters: 32
  projection_dim: 100
  actor_lr: 0.0003
  actor_beta: 0.9
  actor_update_freq: 2
  critic_lr: 0.0003
  critic_beta: 0.9
  critic_tau: 0.005
  critic_target_update_freq: 2
  alpha_lr: 0.0003
  alpha_beta: 0.5

# select algo mode of observation
algo:
  seed: 42
  mode: visual
  train_steps: 1000000 # capacity for replay buffer
  init_steps: 1000
  batch_size: 128 # batch for replay buffer
  save_freq: 100000
  eval_freq: 50000
  # eval_episodes: 1
  eval_episodes: 30
  crop: true
  image_crop_size: 124
  log_dir: logs
  save_video: true
  use_wandb: true
  save_buffer: false
