algorithm: vanilla_state_sac

env:
  category: metaworld
  env_id: pick-place-v2
  frame_stack: 3
  mode: rgb
  image_size: 140
  camera_id: 2

agent:
  name: state_sac
  discount: 0.99
  init_temperature: 0.1
  hidden_dim: 512
  actor_lr: 0.0003
  actor_beta: 0.9
  actor_update_freq: 2
  critic_lr: 0.0003
  critic_beta: 0.9
  critic_tau: 0.005
  critic_target_update_freq: 2
  alpha_lr: 0.0003
  alpha_beta: 0.5

algo:
  seed: 42
  mode: state
  train_steps: 1000000
  init_steps: 1000
  batch_size: 128
  save_freq: 100000
  eval_freq: 50000
  # eval_episodes: 1
  eval_episodes: 30
  crop: false
  image_crop_size: 140
  log_dir: logs
  save_video: true
  use_wandb: false #
