algorithm: multitask_crd_bc

env:
  category: metaworld
  num_task: 5
  env_ids: [
    button-press-topdown-v2,
    drawer-close-v2,
    drawer-open-v2,
    window-close-v2,
    window-open-v2,
  ]
  frame_stack: 3
  mode: rgb
  image_size: 140
  camera_id: 2

agent:
  name: multitask_crd_bc
  use_aug: ${algo.crop}
  num_task: ${env.num_task}
  hidden_dim: 1024
  num_shared_layers: 11
  num_head_layers: 0
  num_filters: 32
  projection_dim: 100
  actor_beta: 0.9
  bc_lr: 0.001
  lambda_crd: 0.8
  s_dims: [1024, 1024, 1024, 1024, 1024, 1024]
  t_dims: [512, 512, 512, 512, 512, 512]
  # crd_weight: [
  #   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  #   [0.0, 0.0, 0.5, 0.0, 0.0, 0.0],
  #   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  #   [0.0, 0.0, 0.0, 0.0, 0.5, 0.0],
  #   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  #   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  # ]
  crd_weight: [
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.5, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.5]
  ]
  feat_dim: ${algo.feature_dim}
  nce_k: 4096
  n_data: 100000 # depends on the expert buffer size
  T: 0.07
  # T: 10
  momentum: 0.5
  # whether to store the contrastive memory in gpu
  # in gpu will consume 10G+ memory, but in cpu will consume 10 times more time
  contrastive_memory_in_gpu: true
  mode: "visual"
  visual_contrastive_task: false

expert:
  model_paths: {
    'button-press-topdown-v2': ./ckpts/multitask/button-press-topdown-v2.pt,
    'drawer-close-v2': ./ckpts/multitask/drawer-close-v2.pt,
    'drawer-open-v2': ./ckpts/multitask/drawer-open-v2.pt,
    'window-close-v2': ./ckpts/multitask/window-close-v2.pt,
    'window-open-v2': ./ckpts/multitask/window-open-v2.pt,
  }
  buffer_paths: {
    'button-press-topdown-v2': ./buffers/multitask/button-press-topdown-v2.pkl,
    'drawer-close-v2': ./buffers/multitask/drawer-close-v2.pkl,
    'drawer-open-v2': ./buffers/multitask/drawer-open-v2.pkl,
    'window-close-v2': ./buffers/multitask/window-close-v2.pkl,
    'window-open-v2': ./buffers/multitask/window-open-v2.pkl,
  }

algo:
  seed: 42
  train_steps: 100000 # 500000
  batch_size: 128
  save_freq: 20000
  eval_freq: 10000
  # eval_episodes: 1
  eval_episodes: 0
  feature_dim: 512
  crop: weak
  image_crop_size: 124
  log_dir: logs
  save_video: true #
  use_wandb: false #
