algorithm: pure_crd

env:
  domain_name: finger
  task_name: spin
  frame_stack: 3
  action_repeat: 4
  image_size: 100
  episode_length: 1000
  eval_mode: null
  distracting_cs_intensity: 0.1

agent:
  name: pure_crd
  load_path: ./ckpts/pure_no_last.pt
  use_aug: ${algo.crop}
  hidden_dim: 1024
  num_shared_layers: 11
  num_head_layers: 0
  num_filters: 32
  projection_dim: 100
  actor_beta: 0.9
  bc_lr: 0.001 # bc for last layer
  crd_lr: 0.001
  s_dim: ${agent.hidden_dim}
  t_dim: 256
  feat_dim: ${algo.feature_dim}
  nce_k: ${algo.K}
  n_data: 50000 # depends on the expert buffer size
  mode: "visual" # not used

expert:
  name: state_sac
  mode: "state" # not used
  hidden_dim: 256 # not used
  model_path: ./ckpts/state_v1.pt
  buffer_path: ./buffers/50000_v1.pkl

baseline:
  name: vanilla_bc
  load_path: ckpts/bc.pt
  use_aug: ${algo.crop}
  hidden_dim: 1024
  num_shared_layers: 11
  num_head_layers: 0
  num_filters: 32
  projection_dim: 100
  actor_beta: 0.9
  bc_lr: 0.001
  crd_baseline_lr: 0.001
  s_dim: ${agent.hidden_dim}
  t_dim: 256
  feat_dim: ${algo.feature_dim}
  nce_k: ${algo.K}
  n_data: 50000 # depends on the expert buffer size
  mode: "visual" # not used

algo:
  seed: 42
  baseline_bc_steps: 200000
  # baseline_bc_steps: 5
  baseline_feat_steps: 5000 # finetune
  # baseline_feat_steps: 5
  agent_feat_steps: 200000 # finetune
  # agent_feat_steps: 5000
  feat_num: 1000
  agent_last_layer_steps: 5000 # finetune
  # agent_last_layer_steps: 5
  agent_eval_freq: 1000
  batch_size: 128
  eval_episodes: 30
  # eval_episodes: 1
  feature_dim: 256
  K: 4096
  T: 0.07
  # T: 0.3
  momentum: 0.5
  crop: true
  image_crop_size: 84
  log_dir: logs
  save_video: true #
  use_wandb: false #
