algorithm: pure_crd

env:
  category: custom_metaworld
  env_id: door-close-v2
  robust: false
  frame_stack: 3
  mode: rgb
  image_size: 140
  camera_id: 2

agent:
  name: pure_crd
  use_aug: ${algo.crop}
  hidden_dim: 1024
  num_shared_layers: 11
  num_head_layers: 0
  num_filters: 32
  projection_dim: 100
  actor_beta: 0.9
  bc_lr: 0.001 # bc for last layer
  use_crd: true
  lambda_crd: 1.0 # crd weight
  crd_lr: 0.001
  s_dims: [1024, 1024, 1024]
  t_dims: [512, 512, 512]
  crd_weight: [
    [0.0, 0.0, 0.0],
    [0.0, 0.5, 0.0],
    [0.0, 0.0, 0.5],
  ]
  feat_dim: ${algo.feature_dim}
  nce_k: 4096
  n_data: 20000 # depends on the expert buffer size
  T: 0.07
  momentum: 0.5
  use_edge_sim: false
  lambda_es: 1.0
  es_weight: [
    [0.3, 0.0, 0.0],
    [0.0, 0.3, 0.0],
    [0.0, 0.0, 0.4],
  ]
  es_size: 128
  es_normalize: true
  # whether to store the contrastive memory in gpu
  contrastive_memory_in_gpu: true
  use_expert_action: true
  mode: "visual" # not used

expert:
  name: state_sac
  mode: "state" # not used
  hidden_dim: 512 # not used
  model_path: ./ckpts/custom_metaworld/door-close-v2/door-close-v2-level-3.pt
  buffer_path: ./buffers/custom_metaworld/door-close-v2/door-close-v2.pkl

algo:
  seed: 42
  agent_feat_steps: 100000 # finetune
  # agent_feat_steps: 1
  feat_num: 1000
  agent_last_layer_steps: 10000 # finetune
  # agent_last_layer_steps: 5
  agent_eval_freq: 2000
  batch_size: 128
  eval_episodes: 1
  feature_dim: 512
  crop: weak
  image_crop_size: 124
  log_dir: logs
  save_video: true #
  use_wandb: false #
