algorithm: vanilla_state_sac

# env:
#   category: dmc
#   domain_name: finger
#   task_name: spin
#   frame_stack: 3
#   action_repeat: 4
#   image_size: 100
#   episode_length: 1000
#   eval_mode: null
#   distracting_cs_intensity: 0

env:
  category: maniskill
  env_id: PickCube-v0
  frame_stack: 3
  control_mode: pd_joint_delta_pos
  render_mode: human
  renderer_kwargs: {'offscreen_only': True}

agent:
  name: state_sac
  discount: 0.99
  init_temperature: 0.3
  hidden_dim: 256
  actor_lr: 0.001
  actor_beta: 0.9
  actor_update_freq: 2
  critic_lr: 0.001
  critic_beta: 0.9
  critic_tau: 0.03
  critic_target_update_freq: 2
  alpha_lr: 0.0001
  alpha_beta: 0.5

algo:
  seed: 42
  mode: state
  train_steps: 500000
  init_steps: 100
  batch_size: 128
  save_freq: 100000
  eval_freq: 10000
  eval_episodes: 1
  crop: false
  image_crop_size: 100
  log_dir: logs
  save_video: false
  use_wandb: false #
