algorithm: vanilla_bc

env:
  domain_name: finger
  task_name: spin
  frame_stack: 3
  action_repeat: 4
  image_size: 100
  episode_length: 1000
  eval_mode: null
  distracting_cs_intensity: 0.1

agent:
  name: vanilla_bc # not used
  use_aug: ${algo.crop}
  discount: 0.99 
  init_temperature: 0.1 
  hidden_dim: 1024 
  num_shared_layers: 11 
  num_head_layers: 0 
  num_filters: 32 
  projection_dim: 100 
  actor_lr: 0.001 
  actor_beta: 0.9 
  actor_update_freq: 2 
  critic_lr: 0.001 
  critic_beta: 0.9
  critic_tau: 0.03 
  critic_target_update_freq: 2 
  alpha_lr: 0.0001
  alpha_beta: 0.5
  bc_lr: 0.001 # bc
  mode: "visual" # not used

expert:
  name: state_sac # ! used in code
  mode: "state" # not used
  hidden_dim: 256 # not used
  model_path: "./logs/finger_spin/vanilla_state_sac/42/2023-11-22 17:17:19.662577/model/200000.pt"
  buffer_path: "./logs/finger_spin/vanilla_state_sac/42/2023-11-22 17:17:19.662577/replay_buffer/replay_buffer.pkl"

algo:
  seed: 42
  train_steps: 200000 # 500000
  batch_size: 128
  save_freq: 50000
  eval_freq: 10000
  eval_episodes: 30
  crop: true
  image_crop_size: 84
  log_dir: logs
  save_video: true #
  use_wandb: true #