algorithm: vanilla_bc_strong_aug

env:
  category: dmc
  env_id: finger_spin
  domain_name: finger
  task_name: spin
  frame_stack: 3
  action_repeat: 4
  image_size: 100
  episode_length: 1000
  eval_mode: distracting_cs
  distracting_cs_intensity: 0.1

agent:
  name: vanilla_bc # not used
  use_aug: ${algo.crop}
  hidden_dim: 1024 
  num_shared_layers: 11 
  num_head_layers: 0 
  num_filters: 32 
  projection_dim: 100 
  actor_beta: 0.9 
  bc_lr: 0.001 # bc
  mode: "visual" # not used
  visual_contrastive_task: false # visual task for encoder

expert:
  buffer_path: ./buffers/50000_plain.pkl # you may need to re-collect

algo:
  seed: 42
  train_steps: 200000 # 500000
  save_freq: 50000
  eval_freq: 10000
  # eval_episodes: 1
  eval_episodes: 30
  crop: "strong" # or None for not use any aug, "weak" for just use crop
  image_crop_size: 84
  log_dir: logs
  save_video: true #
  use_wandb: true #
