algorithm: vanilla_bc

env:
  domain_name: finger
  task_name: spin
  frame_stack: 3
  action_repeat: 4
  image_size: 100
  episode_length: 1000
  eval_mode: null
  distracting_cs_intensity: 0.1

agent:
  name: vanilla_bc # not used
  use_aug: ${algo.crop}
  hidden_dim: 1024 
  num_shared_layers: 11 
  num_head_layers: 0 
  num_filters: 32 
  projection_dim: 100 
  actor_beta: 0.9 
  bc_lr: 0.001 # bc
  mode: "visual" # not used

expert:
  buffer_path: ./buffers/50000.pkl

algo:
  seed: 42
  train_steps: 200000 # 500000
  save_freq: 50000
  eval_freq: 10000
  eval_episodes: 30
  crop: true
  image_crop_size: 84
  log_dir: logs
  save_video: true #
  use_wandb: true #
