algorithm: vanilla_bc

env:
  category: custom_metaworld
  env_id: window-close-v2
  robust: false
  frame_stack: 3
  mode: rgb
  image_size: 140
  camera_id: 2

agent:
  name: vanilla_bc # not used
  use_aug: ${algo.crop}
  hidden_dim: 1024 
  num_shared_layers: 11 
  num_head_layers: 0 
  num_filters: 32 
  projection_dim: 100 
  actor_beta: 0.9 
  bc_lr: 0.001 # bc
  mode: "visual" # not used
  visual_contrastive_task: false # visual task for encoder

expert:
  buffer_path: ./buffers/custom_metaworld/diversity/window-close-v2/diversity_3.pkl # you may need to re-collect

algo:
  seed: 42
  train_steps: 100000 # 500000
  save_freq: 20000
  eval_freq: 10000
  # eval_episodes: 1
  eval_episodes: 0
  crop: weak # or None for not use any aug, "weak" for just use crop
  image_crop_size: 124
  log_dir: logs
  save_video: true #
  use_wandb: false #
